"""
Bundle the review app's front end into the one HTML file Apps Script serves (phase 2).

    python review_app/bundle.py [--check] [--out FILE] [--project FILE]

Apps Script's HtmlService serves a single file, so review_app/web/{index.html, style.css, gas.js,
app.js} are inlined into review_app/gas/index.html. That file is GENERATED and gitignored (web/ is
the one source, and it changes often): never edit it by hand, and run this right before every
deploy (clasp pushes review_app/gas/ as it is; a paste deploy copies the file). The local stand-in
(review_app/gas_dev/dev_server.js) runs it at start. --check writes nothing and exits 1 when the
bundle on disk is not what web/ would produce now: run it before `clasp push`.

It also writes review_app/gas/Config.gs (generated, gitignored) from review_app/google.json: the two
Drive IDs Code.gs needs (`data_folder_id`, `store_sheet_id`), so nobody types them into Script
Properties. With either ID missing no Config.gs is written (and a stale one is removed).

--project FILE writes the whole script project (Code, Config, appsscript, index) as the JSON a
Drive import takes (media type application/vnd.google-apps.script+json): a Drive `files.create` /
`files.update` with it creates or replaces the project's files without clasp or a paste.
"""
import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
WEB = HERE / "web"
GAS = HERE / "gas"
OUT = GAS / "index.html"
CONFIG_GS = GAS / "Config.gs"
GOOGLE_JSON = HERE / "google.json"
PROJECT_MIME = "application/vnd.google-apps.script+json"
BANNER = "<!-- GENERATED by review_app/bundle.py from review_app/web/: do not edit; edit web/ and re-run -->\n"
CSS_TAG = '<link rel="stylesheet" href="style.css">'
SCRIPTS = ("gas.js", "app.js")


def _inline_js(name, web):
    text = (web / name).read_text(encoding="utf-8")
    # an inline script ends at the first "</script" whatever the JS meant by it
    if re.search(r"</script", text, re.I) or "<!--" in text:
        raise SystemExit(f"{name}: contains '</script' or '<!--', which would break an inline <script>: "
                         "split the string ('<' + '/script>')")
    return f"<script>\n{text.rstrip()}\n</script>"


def bundle(web=WEB):
    web = Path(web)
    html = (web / "index.html").read_text(encoding="utf-8")
    css = (web / "style.css").read_text(encoding="utf-8")
    if "</style" in css.lower():
        raise SystemExit("style.css: contains '</style'")
    if html.count(CSS_TAG) != 1:
        raise SystemExit(f"index.html: expected exactly one {CSS_TAG}")
    # links leave the sandboxed iframe: a bare link would try to navigate the frame itself
    html = html.replace(CSS_TAG, f'<base target="_top">\n<style>\n{css.rstrip()}\n</style>')
    for name in SCRIPTS:
        tag = f'<script src="{name}"></script>'
        if html.count(tag) != 1:
            raise SystemExit(f"index.html: expected exactly one {tag}")
        html = html.replace(tag, _inline_js(name, web))
    left = re.findall(r'<(?:script|link)[^>]+(?:src|href)="(?!https?:)[^"]*"', html.split("<script>")[0])
    if left:
        raise SystemExit(f"index.html still references local files the bundle cannot serve: {left}")
    return html.replace("<!doctype html>\n", "<!doctype html>\n" + BANNER, 1)


def config_gs(cfg):
    """Config.gs for these IDs, or None when either is missing."""
    ids = {"DATA_FOLDER_ID": (cfg or {}).get("data_folder_id") or "", "STORE_SHEET_ID": (cfg or {}).get("store_sheet_id") or ""}
    if not all(ids.values()):
        return None
    be = (cfg or {}).get("backend") or {}
    if be.get("sheet_id"):       # the live drift check reads the backend tracker sheet (read-only use)
        ids["BACKEND"] = be
    return ("// GENERATED by review_app/bundle.py from review_app/google.json: do not edit\n"
            f"var CONFIG_ = {json.dumps(ids, indent=2)};\n")


def read_config(path=GOOGLE_JSON):
    p = Path(path)
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else {}


def project(html, config, gas=GAS):
    """The script project as a Drive import body: {"files": [{name, type, source}]}."""
    files = [{"name": "appsscript", "type": "json", "source": (Path(gas) / "appsscript.json").read_text(encoding="utf-8")},
             {"name": "Code", "type": "server_js", "source": (Path(gas) / "Code.gs").read_text(encoding="utf-8")}]
    if config:
        files.append({"name": "Config", "type": "server_js", "source": config})
    files.append({"name": "index", "type": "html", "source": html})
    return {"files": files}


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="write nothing; exit 1 if gas/index.html is out of date")
    ap.add_argument("--out", default=None, help="write (or check) this file instead of review_app/gas/index.html")
    ap.add_argument("--project", default=None, help="also write the whole project as a Drive import JSON to this file")
    ap.add_argument("--config", default=None, help="default review_app/google.json")
    a = ap.parse_args(argv)
    out = Path(a.out) if a.out else OUT
    cfg_out = out.parent / CONFIG_GS.name
    html = bundle()
    config = config_gs(read_config(a.config or GOOGLE_JSON))
    if a.check:
        stale = [p for p, want in ((out, html), (cfg_out, config))
                 if (p.read_text(encoding="utf-8") if p.exists() else None) != want]
        for p in stale:
            print(f"{p} is out of date: python review_app/bundle.py", file=sys.stderr)
        return 1 if stale else 0
    out.write_text(html, encoding="utf-8")
    print(f"wrote {out} ({len(html.encode('utf-8')):,} bytes)")
    if config:
        cfg_out.write_text(config, encoding="utf-8")
        print(f"wrote {cfg_out}")
    elif cfg_out.exists():
        cfg_out.unlink()
        print(f"removed {cfg_out} (google.json names no data folder / store)")
    if a.project:
        Path(a.project).write_text(json.dumps(project(html, config), ensure_ascii=False), encoding="utf-8")
        print(f"wrote {a.project} (Drive import, media type {PROJECT_MIME})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
