#!/usr/bin/env python3
"""Regenerate narrative counts from the staged JSON stores (the canonical
pending-state). Country notes / CLAUDE.md quote these numbers instead of
hand-maintaining them — when the artifacts and the narrative disagree, THIS
output wins (it is derived, never edited).

    python scripts/staged_summary.py --country Egypt --commodity gas
    python scripts/staged_summary.py --all --format md
    python scripts/staged_summary.py --country Iran --commodity gas --format json
    python scripts/staged_summary.py --index          # regenerate batches/INDEX.md

Formats:
  text  (default) per-dir + rolled-up counts, human-readable
  md    same, fenced in <!-- staged-summary:start scope=<slug> --> markers for
        idempotent splicing into docs/country_notes/<country>.md
  json  machine-readable (per-dir + rollup)
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import normalize as N  # noqa: E402
from staged_store import (  # noqa: E402
    BATCHES_ROOT, _STATUS_PENDING, _STORE_FILES, _dir_mode, _dir_scope,
    dir_label, discover_staging_dirs, load_staged_context, scope_dirname,
)


def _dir_summary(d: Path) -> dict:
    ctx = load_staged_context([d])
    concerns = [c for cs in ctx["concerns"].values() for c in cs]
    status = [r for rs in ctx["status_changes"].values() for r in rs]
    return {
        "dir": dir_label(d),
        "researched_pids": len(ctx["researched_pids"]),
        "concerns_by_type": dict(Counter(c["concern_type"] for c in concerns)),
        "status_verdicts": dict(Counter(r.get("verdict", "") for r in status)),
        "status_changes_pending": sum(
            1 for r in status if r.get("verdict", "") in _STATUS_PENDING),
        "fills": len(ctx["fills"]),
        "updates": len(ctx["updates"]),
        "ref_work_by_class": dict(ctx["ref_counts"]),
        "route_suggestions": len(ctx["route_staged"]),
        "new_rows_by_class": dict(
            Counter(c.get("class", "") for c in ctx["new_rows"])),
    }


def _rollup(per_dir: list[dict]) -> dict:
    roll: dict = {"dirs": [s["dir"] for s in per_dir]}
    for key in ("concerns_by_type", "status_verdicts", "ref_work_by_class",
                "new_rows_by_class"):
        total: Counter = Counter()
        for s in per_dir:
            total.update(s[key])
        roll[key] = dict(total)
    for key in ("status_changes_pending", "fills", "updates",
                "route_suggestions"):
        roll[key] = sum(s[key] for s in per_dir)
    return roll


def _fmt_counts(d: dict) -> str:
    return ", ".join(f"{k}={v}" for k, v in sorted(d.items())) if d else "none"


def _text_block(scope_label: str, per_dir: list[dict], roll: dict,
                md: bool = False) -> list[str]:
    b = "- " if md else "  "
    lines = [f"## Staged summary — {scope_label}" if md
             else f"=== {scope_label} ==="]
    lines += [
        f"{b}staging dirs: {', '.join(roll['dirs'])}",
        f"{b}concerns: {_fmt_counts(roll['concerns_by_type'])}",
        f"{b}status verdicts: {_fmt_counts(roll['status_verdicts'])} "
        f"({roll['status_changes_pending']} pending changes)",
        f"{b}fills (corroborated): {roll['fills']}",
        f"{b}update changes (§5): {roll['updates']}",
        f"{b}ref work: {_fmt_counts(roll['ref_work_by_class'])}",
        f"{b}route suggestions: {roll['route_suggestions']}",
        f"{b}discovery: {_fmt_counts(roll['new_rows_by_class'])}",
    ]
    for s in per_dir:
        lines.append(f"{b}[{s['dir']}] rows={s['researched_pids']} "
                     f"concerns({_fmt_counts(s['concerns_by_type'])}) "
                     f"status({_fmt_counts(s['status_verdicts'])}) "
                     f"fills={s['fills']} updates={s['updates']} "
                     f"refs({_fmt_counts(s['ref_work_by_class'])}) "
                     f"routes={s['route_suggestions']} "
                     f"new({_fmt_counts(s['new_rows_by_class'])})")
    return lines


def _all_scopes(root: Path) -> dict[tuple, list[Path]]:
    """Every (country, commodity) with primary staged work (batches/*/staging/*)."""
    scopes: dict[tuple, list[Path]] = {}
    if not root.is_dir():
        return scopes
    for d in sorted(root.glob("*/staging/*")):
        if not d.is_dir():
            continue
        scope = _dir_scope(d)
        if scope is None or _dir_mode(d) in ("qc", "handoff"):
            continue
        scopes.setdefault(scope, []).append(d)
    return scopes


def _index_lines(root: Path) -> list[str]:
    """batches/INDEX.md content: per scope dir — staging runs (with pending
    counts), input runs, assembled packets, deliverables, archive."""
    lines = [
        "# Batches index",
        "",
        "Regenerated by `python scripts/staged_summary.py --index` — never",
        "hand-edit. Layout: `batches/<country>-<commodity>/` holds",
        "`staging/<mode[-qualifier]>/` (pending work + recon inputs),",
        "`deliverables/` (current workbooks), `archive/` (superseded or",
        "applied). See docs/workflows.md \"Batch artifacts\".",
    ]
    for scope_dir in sorted(p for p in root.iterdir() if p.is_dir()):
        subdirs = {n: scope_dir / n for n in ("staging", "deliverables", "archive")}
        if not any(p.is_dir() for p in subdirs.values()):
            continue
        lines += ["", f"## {scope_dir.name}", ""]
        staging = subdirs["staging"]
        if staging.is_dir():
            for d in sorted(p for p in staging.iterdir() if p.is_dir()):
                rel = f"staging/{d.name}"
                if not any((d / fn).exists() for fn in _STORE_FILES):
                    kind = ("recon inputs" if d.name.startswith("recon-")
                            else "no store — invisible to discovery")
                    lines.append(f"- `{rel}` — {kind}")
                    continue
                mode = _dir_mode(d)
                s = _dir_summary(d)
                counts = (f"rows={s['researched_pids']} fills={s['fills']} "
                          f"updates={s['updates']} "
                          f"status-pending={s['status_changes_pending']} "
                          f"refs({_fmt_counts(s['ref_work_by_class'])}) "
                          f"routes={s['route_suggestions']} "
                          f"new({_fmt_counts(s['new_rows_by_class'])})")
                tag = f" [assembled packet: {mode}]" if mode in ("qc", "handoff") \
                    else (f" [{mode}]" if mode else "")
                lines.append(f"- `{rel}`{tag} — {counts}")
        for kind in ("deliverables", "archive"):
            p = subdirs[kind]
            files = sorted(f.name for f in p.iterdir()
                           if f.is_file() and not f.name.startswith(".")) \
                if p.is_dir() else []
            if not files:
                continue
            if kind == "archive":
                lines.append(f"- `archive/` — {len(files)} superseded/applied "
                             "file(s)")
            else:
                lines += [f"- `{kind}/{f}`" for f in files]
    return lines


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--country")
    ap.add_argument("--commodity", choices=["gas", "oil"])
    ap.add_argument("--all", action="store_true",
                    help="every (country, commodity) scope with staged work")
    ap.add_argument("--index", action="store_true",
                    help="regenerate batches/INDEX.md (the whole-tree lookup)")
    ap.add_argument("--format", default="text", choices=["text", "md", "json"])
    ap.add_argument("--root", default=str(BATCHES_ROOT))
    args = ap.parse_args()

    if not args.index and not args.all and not (args.country and args.commodity):
        ap.error("--country + --commodity, --all, or --index")

    root = Path(args.root)
    if args.index:
        out = root / "INDEX.md"
        out.write_text("\n".join(_index_lines(root)) + "\n")
        print(f"wrote {out}")
        return
    if args.all:
        scopes = _all_scopes(root)
    else:
        dirs = discover_staging_dirs(args.country, args.commodity, root=root)
        scopes = {(N.normalize_country(args.country), args.commodity): dirs}

    out_json = {}
    for (country, commodity), dirs in sorted(scopes.items()):
        per_dir = [_dir_summary(d) for d in dirs]
        roll = _rollup(per_dir)
        slug = scope_dirname(country, commodity)
        label = f"{country} ({commodity})"
        if args.format == "json":
            out_json[slug] = {"country": country, "commodity": commodity,
                              "rollup": roll, "per_dir": per_dir}
        elif args.format == "md":
            print(f"<!-- staged-summary:start scope={slug} -->")
            print("\n".join(_text_block(label, per_dir, roll, md=True)))
            print(f"<!-- staged-summary:end scope={slug} -->")
            print()
        else:
            print("\n".join(_text_block(label, per_dir, roll)))
            print()
    if args.format == "json":
        print(json.dumps(out_json, indent=1, ensure_ascii=False))


if __name__ == "__main__":
    main()
