/**
 * Pipelines review app, Google side (phase 2). Apps Script web app: execute as the deploying
 * user, access limited to the domain (appsscript.json). The page is index.html, generated by
 * review_app/bundle.py from review_app/web/.
 *
 * This script touches exactly two Drive objects, both named in Config.gs (generated by
 * review_app/bundle.py from review_app/google.json; a Script Property of the same name overrides):
 *   DATA_FOLDER_ID  the folder review_app/publish.py writes. READ-ONLY here.
 *   STORE_SHEET_ID  the decision store spreadsheet. One tab, `log`: append-only, one row per
 *                   decision record, the same record review_log.jsonl holds locally.
 * It never opens the backend tracker sheet, never calls UrlFetchApp, never deletes or edits a row.
 *
 * The validation here is a port of review_app/store.py (validate / validate_items / decide):
 * tests/test_review_gas.py runs both against the same requests and compares the records.
 * What a line may lock on or resolve is precomputed by publish.py (the scope's index file, packed
 * by publish.pack_index and unpacked one entry at a time by get_ here), so the column logic lives
 * in Python only.
 */
var LOG_TAB = 'log';
var COLS = ['ts', 'reviewer', 'rec', 'pid', 'sheet_row', 'ref_col', 'kind', 'decision', 'call', 'suggested_value',
            'note', 'undecided', 'via', 'batch', 'snapshot', 'key', 'id', 'scope', 'json'];
var SCOPE_COL = COLS.indexOf('scope') + 1;      // `scope` and `json` are adjacent: one read gets both
var DECISIONS = ['accept', 'hold', 'reject', 'suggest'];
var LINE_KINDS = ['ref', 'fill', 'status', 'oo', 'route', 'new_row'];
var CONCERN_CALLS = ['confirmed', 'dismissed', 'needs_research'];
var OTHER_CALLS = ['noted', 'todo', 'dismissed'];
var MAX_TEXT = 5000;         // note / suggested value length (a sheet cell holds 50,000 characters)
var MAX_RECORDS = 5000;      // one request
var CACHE_CHUNK = 90000;     // CacheService holds 100 KB per value
var CAPS = {decide: true, refresh: false, push: false};
var MEMO_ = {};              // per execution

function doGet(e) {
  if (e && e.parameter && e.parameter.spike) return spikePage_();
  return HtmlService.createHtmlOutputFromFile('index').setTitle('pipelines reviewer')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}

// ---- small helpers ---------------------------------------------------------------

function refuse_(code, message, extra) {
  var e = new Error(message);
  e.refusal = true; e.code = code; e.extra = extra || {};
  return e;
}
function answer_(fn) {
  try {
    var out = fn();
    out.ok = true;
    return out;
  } catch (e) {
    if (!e || !e.refusal) throw e;
    var body = {ok: false, code: e.code, error: e.message};
    Object.keys(e.extra).forEach(function (k) { body[k] = e.extra[k]; });
    return body;
  }
}
function prop_(name) {
  var v = PropertiesService.getScriptProperties().getProperty(name);
  // Config.gs is generated by review_app/bundle.py from review_app/google.json; a Script Property overrides it
  if (!v && typeof CONFIG_ !== 'undefined') v = CONFIG_[name];
  if (!v) throw refuse_(500, name + ' is not set: run review_app/bundle.py with google.json filled in, or set the ' +
                        'script property (Project Settings > Script Properties)');
  return v;
}
function me_() {
  var email = Session.getActiveUser().getEmail();
  if (!email) throw refuse_(403, 'Google did not say who you are: sign in with your work account and reload');
  return String(email).toLowerCase();
}
function now_() {
  return Utilities.formatDate(new Date(), 'America/New_York', "yyyy-MM-dd'T'HH:mm:ssXXX");
}
function has_(o, k) { return Object.prototype.hasOwnProperty.call(o, k); }

// ---- the published dataset (Drive folder, read-only) -------------------------------

function file_(name) {
  if (MEMO_['f:' + name]) return MEMO_['f:' + name];
  var it = DriveApp.getFolderById(prop_('DATA_FOLDER_ID')).getFilesByName(name), best = null;
  while (it.hasNext()) {                 // Drive allows two files with one name: take the newest
    var f = it.next();
    if (f.isTrashed()) continue;         // publish.py trashes superseded versions
    if (!best || f.getLastUpdated().getTime() > best.getLastUpdated().getTime()) best = f;
  }
  if (!best) throw refuse_(404, 'not in the data folder: ' + name + ' (the scope was republished: reload the page)');
  MEMO_['f:' + name] = best;
  return best;
}
function cacheGetBig_(key) {
  var c = CacheService.getScriptCache(), n = Number(c.get(key + ':n'));
  if (!n) return null;
  var keys = [], i;
  for (i = 0; i < n; i++) keys.push(key + ':' + i);
  var got = c.getAll(keys), parts = [];
  for (i = 0; i < n; i++) {
    if (got[keys[i]] == null) return null;
    parts.push(got[keys[i]]);
  }
  return parts.join('');
}
function cachePutBig_(key, text, seconds) {
  var m = {}, n = Math.ceil(text.length / CACHE_CHUNK);
  for (var i = 0; i < n; i++) m[key + ':' + i] = text.substr(i * CACHE_CHUNK, CACHE_CHUNK);
  m[key + ':n'] = String(n);
  try { CacheService.getScriptCache().putAll(m, seconds); } catch (e) { /* too big to cache: read Drive each time */ }
}
function scopes_() {
  if (MEMO_.scopes) return MEMO_.scopes;
  var text = cacheGetBig_('scopes');
  if (!text) {
    try { text = file_('scopes.json').getBlob().getDataAsString('UTF-8'); }
    catch (e) { if (e.refusal && e.code === 404) text = '{"scopes": []}'; else throw e; }
    cachePutBig_('scopes', text, 60);       // a publish shows up within a minute
  }
  MEMO_.scopes = JSON.parse(text).scopes || [];
  return MEMO_.scopes;
}
function scope_(id) {
  var found = null;
  scopes_().forEach(function (s) { if (s.id === id) found = s; });
  if (!found) throw refuse_(404, 'no published scope ' + JSON.stringify(id));
  return found;
}
function index_(sc) {
  var ck = 'idx:' + sc.id + ':' + sc.ver;
  if (MEMO_[ck]) return MEMO_[ck];
  var text = cacheGetBig_(ck);
  if (!text) {
    text = file_(sc.index).getBlob().getDataAsString('UTF-8');
    cachePutBig_(ck, text, 21600);
  }
  MEMO_[ck] = JSON.parse(text);
  return MEMO_[ck];
}
/** One key's entry from the packed index (publish.pack_index), or null. A line:
 *  {g:'l', kind, dir, pid, sheet_row, ref_col, def, basis, covers: [{key, dir, sheet_row, ref_col, kind}],
 *   lock: [{c: concern key, held: [col], res: [col]}]}; an item: {g:'i', kind, dir, pid, call0}. */
function get_(I, key) {
  if (typeof key !== 'string') return null;
  if (!I.m) {
    I.m = {}; I.dn = {};
    I.dirs.forEach(function (d, i) { I.dn[d] = i; });
  }
  if (has_(I.m, key)) return I.m[key];
  var at = key.indexOf('::'), out = null;
  if (at > 0) {
    var dir = key.substr(0, at), rest = key.substr(at + 2), grp = has_(I.dn, dir) ? I.keys[I.dn[dir]] : null;
    if (grp && has_(grp, rest)) {
      var c = grp[rest];
      out = c.i ? {g: 'i', kind: c.i, dir: dir, pid: c.p, call0: c.c0 || ''}
        : {g: 'l', kind: c.k, dir: dir, pid: c.p, sheet_row: c.r == null ? null : c.r, ref_col: c.c || '',
           def: c.d || 'accept', basis: c.b || '',
           covers: (c.v || []).map(function (x) {
             return {key: x[0], dir: x[0].substr(0, x[0].indexOf('::')), sheet_row: x[1] == null ? null : x[1], ref_col: x[2] || '', kind: x[3]};
           }),
           lock: (c.l || []).map(function (x) { return {c: x[0], held: x[1] || [], res: x[2] || []}; })};
    }
  }
  I.m[key] = out;
  return out;
}

// ---- the decision store (spreadsheet, append-only) ---------------------------------

function log_(create) {
  if (MEMO_.log) return MEMO_.log;
  var ss = SpreadsheetApp.openById(prop_('STORE_SHEET_ID')), sh = ss.getSheetByName(LOG_TAB);
  if (!sh && !create) return null;
  if (!sh) {
    sh = ss.insertSheet(LOG_TAB);
    if (sh.getMaxColumns() > COLS.length) sh.deleteColumns(COLS.length + 1, sh.getMaxColumns() - COLS.length);
    // plain text everywhere: a timestamp, a number or a leading "=" must stay the text that was written
    sh.getRange(1, 1, sh.getMaxRows(), COLS.length).setNumberFormat('@').setFontFamily('Calibri').setFontSize(10);
    sh.getRange(1, 1, 1, COLS.length).setValues([COLS]).setFontWeight('bold');
    sh.setFrozenRows(1);
  }
  MEMO_.log = sh;
  return sh;
}
/** Records of one scope stored after sheet row `after`: {last: <last sheet row>, recs: [record + row]}. */
function rows_(sc, after) {
  var sh = log_(false), out = {last: 1, recs: []};
  if (!sh) return out;
  out.last = Math.max(1, sh.getLastRow());
  after = Math.max(1, Number(after) || 0);
  if (out.last <= after) return out;
  var vals = sh.getRange(after + 1, SCOPE_COL, out.last - after, 2).getValues();
  for (var i = 0; i < vals.length; i++) {
    if (vals[i][0] !== sc.id || !vals[i][1]) continue;
    var r;
    try { r = JSON.parse(vals[i][1]); } catch (e) { continue; }
    r.row = after + 1 + i;
    out.recs.push(r);
  }
  return out;
}
function cell_(v) {       // a display column: never a formula, never longer than a cell
  var s = v == null ? '' : String(v);
  if (/^[=+\-@]/.test(s)) s = "'" + s;
  return s.length > 2000 ? s.substr(0, 2000) + '…' : s;
}
function append_(sh, recs) {
  var first = sh.getLastRow() + 1, short = first + recs.length - 1 - sh.getMaxRows();
  if (short > 0) sh.insertRowsAfter(sh.getMaxRows(), short + 500);
  var rows = recs.map(function (r) {
    var j = JSON.stringify(r);
    if (j.length > 49000) throw refuse_(400, 'a record is too long to store: shorten the note');
    return [r.ts, r.reviewer, has_(r, 'call') ? 'item' : 'line', cell_(r.pid), r.sheet_row == null ? '' : String(r.sheet_row),
            cell_(r.ref_col), r.kind, r.decision || '', r.call || '', cell_(r.suggested_value), cell_(r.note),
            r.undecided ? 'undone' : '', cell_(r.via), r.batch, cell_(r.snapshot), cell_(r.key), r.id, r.scope, j];
  });
  sh.getRange(first, 1, rows.length, COLS.length).setNumberFormat('@').setValues(rows);
  SpreadsheetApp.flush();
  recs.forEach(function (r, i) { r.row = first + i; });
  return first + recs.length - 1;
}

// ---- validation: a port of review_app/store.py --------------------------------------

function text_(v, i, what) {
  var s = v ? String(v) : '';
  if (s.length > MAX_TEXT) throw refuse_(400, 'record ' + i + ': the ' + what + ' is longer than ' + MAX_TEXT + ' characters');
  return s;
}
function list_(records, what) {
  if (!Array.isArray(records) || !records.length) throw refuse_(400, 'expected a non-empty list of ' + what + ' records');
  if (records.length > MAX_RECORDS) throw refuse_(400, 'too many records in one request (' + records.length + ')');
}
function entry_(idx, r, i) {
  if (!r || typeof r !== 'object' || Array.isArray(r)) throw refuse_(400, 'record ' + i + ': not an object');
  var e = get_(idx, r.key);
  if (!e) throw refuse_(400, 'record ' + i + ': unknown key ' + JSON.stringify(r.key));
  return e;
}
/** store.validate: normalised line records, each followed by its cover records. `open(key)` says
 *  whether a concern still has no call (the state BEFORE this request). */
function validateLines_(records, idx, open) {
  list_(records, 'decision');
  var out = [];
  records.forEach(function (r, i) {
    var e = entry_(idx, r, i), key = r.key;
    if (e.g !== 'l' || LINE_KINDS.indexOf(e.kind) < 0) throw refuse_(400, 'record ' + i + ': ' + JSON.stringify(key) + ' is an item, not a line');
    var undo = !!(r.undo || r.undecided), decision = r.decision;
    if (undo && !decision) decision = e.def || 'hold';        // an undo record still carries a decision field
    if (!undo && !decision) throw refuse_(400, 'record ' + i + ': no decision given (a bare key never defaults to accept)');
    if (DECISIONS.indexOf(decision) < 0) throw refuse_(400, 'record ' + i + ': decision ' + JSON.stringify(decision) + ' is not one of ' + DECISIONS.join(', '));
    var note = text_(r.note, i, 'note'), sv = text_(r.suggested_value, i, 'suggested value');
    if (decision === 'suggest' && !undo && !(sv.trim() || note.trim())) throw refuse_(400, 'record ' + i + ': a suggestion needs a suggested_value or a note');
    if (decision === 'accept' && !undo) {
      var held = {};
      (e.lock || []).forEach(function (lk) { if (open(lk.c)) (lk.held || []).forEach(function (c) { held[c] = 1; }); });
      held = Object.keys(held).sort();
      if (held.length) throw refuse_(409, 'record ' + i + ': ' + JSON.stringify(key) + ' is held: a validity concern contests ' + held.join(', ') + ' and has no call yet');
    }
    var rec = {key: key, dir: e.dir, pid: e.pid, sheet_row: e.sheet_row == null ? null : e.sheet_row, ref_col: e.ref_col || '',
               kind: e.kind, decision: decision, suggested_value: sv, note: note, reviewer: null, ts: null, undecided: undo};
    if (e.basis) rec.basis = e.basis;
    out.push(rec);
    (e.covers || []).forEach(function (c) {       // store.cover_records: the same call on every covered record
      var cr = {};
      Object.keys(rec).forEach(function (k) { cr[k] = rec[k]; });
      cr.key = c.key; cr.dir = c.dir; cr.sheet_row = c.sheet_row == null ? null : c.sheet_row;
      cr.ref_col = c.ref_col || ''; cr.kind = c.kind; cr.via = key;
      out.push(cr);
    });
  });
  return out;
}
/** store.validate_items */
function validateItems_(records, idx) {
  list_(records, 'item');
  return records.map(function (r, i) {
    var e = entry_(idx, r, i);
    if (e.g !== 'i') throw refuse_(400, 'record ' + i + ': ' + JSON.stringify(r.key) + ' is a line, not an item');
    var undo = !!(r.undo || r.undecided), call = undo ? '' : (r.call ? String(r.call) : '');
    var vocab = e.kind === 'concern' ? CONCERN_CALLS : OTHER_CALLS;
    if (!undo && vocab.indexOf(call) < 0) throw refuse_(400, 'record ' + i + ': call ' + JSON.stringify(call) + ' is not one of ' + vocab.join(', ') + ' for a ' + e.kind + ' item');
    return {key: r.key, dir: e.dir, pid: e.pid, kind: e.kind, call: call, note: text_(r.note, i, 'note'),
            reviewer: null, ts: null, undecided: undo};
  });
}
/** The second half of store.decide: a person's accept of a line that IS the resolution of an open
 *  concern also dismisses that concern, in the same write. */
function selfResolved_(recs, idx, open) {
  var cols = {}, order = [];
  recs.forEach(function (r) {
    if (r.decision !== 'accept' || r.undecided || r.via) return;
    (get_(idx, r.key).lock || []).forEach(function (lk) {
      if (!open(lk.c)) return;
      (lk.res || []).forEach(function (col) {
        if (!cols[lk.c]) { cols[lk.c] = []; order.push(lk.c); }
        if (cols[lk.c].indexOf(col) < 0) cols[lk.c].push(col);
      });
    });
  });
  if (!order.length) return [];
  return validateItems_(order.map(function (k) {
    return {key: k, call: 'dismissed', note: 'resolved by accepted ' + cols[k].join(', ') + ' fill'};
  }), idx);
}

// ---- the write path ------------------------------------------------------------------

function write_(scopeId, ver, records, cursor, items) {
  return answer_(function () {
    var reviewer = me_(), lock = LockService.getScriptLock();
    try { lock.waitLock(25000); } catch (e) { throw refuse_(503, 'the decision store is busy: try again in a moment'); }
    try {
      var sc = scope_(scopeId);
      if (sc.ver !== ver) throw refuse_(409, 'this scope was republished (' + sc.published + '): reload the page', {reload: true, ver: sc.ver});
      var idx = index_(sc), sh = log_(true), st = rows_(sc, sc.store_cursor);
      cursor = Math.max(Number(cursor) || 0, Number(sc.store_cursor) || 1);
      // item calls as of now: the published base, then every stored record since
      var calls = {}, newer = [], theirs = {};
      st.recs.forEach(function (r) {
        if (has_(r, 'call')) calls[r.key] = r.undecided ? '' : r.call;
        if (r.row > cursor) {
          newer.push(r);
          if (r.reviewer !== reviewer) theirs[r.key] = r;
        }
      });
      var open = function (k) {
        var e = get_(idx, k);
        return !!e && !(has_(calls, k) ? calls[k] : e.call0);
      };
      // someone else decided one of these since this page last heard from the store: refuse the
      // whole request, hand the page their records, and let the reviewer look before pressing again
      if (Array.isArray(records)) {
        var clash = records.filter(function (r) { return r && typeof r.key === 'string' && has_(theirs, r.key); });
        if (clash.length) {
          var t = theirs[clash[0].key];
          throw refuse_(409, (clash.length === 1 ? 'this was' : clash.length + ' of these were') + ' decided by ' + t.reviewer +
            ' after your page last synced: nothing was saved. Their call is now shown; press again to replace it.',
            {stale: true, records: newer, cursor: st.last});
        }
      }
      var recs = items ? validateItems_(records, idx) : validateLines_(records, idx, open);
      if (!items) recs = recs.concat(selfResolved_(recs, idx, open));
      var ts = now_(), batch = Utilities.getUuid();
      recs.forEach(function (r) {
        r.reviewer = reviewer; r.ts = ts;
        r.id = Utilities.getUuid(); r.scope = sc.id; r.batch = batch; r.snapshot = sc.snapshot || ''; r.origin = 'gas';
      });
      var last = append_(sh, recs);
      return {saved: recs, others: newer, cursor: last};
    } finally {
      lock.releaseLock();
    }
  });
}

// ---- what the page calls (google.script.run) -------------------------------------------

function whoami() {
  return answer_(function () {
    return {reviewer: me_(), caps: CAPS, scopes: scopes_()};
  });
}
/** One published file of a scope (a gzipped dataset part, or the geometry bundle), base64. */
function getPart(scopeId, ver, name) {
  return answer_(function () {
    me_();
    var sc = scope_(scopeId), names = (sc.parts || []).concat(sc.geo ? [sc.geo] : []);
    if (sc.ver !== ver || names.indexOf(name) < 0) throw refuse_(409, 'this scope was republished (' + sc.published + '): reload the page', {reload: true, ver: sc.ver});
    return {b64: Utilities.base64Encode(file_(name).getBlob().getBytes())};
  });
}
/** Every record of the scope stored after sheet row `after`, oldest first, and the new cursor. */
function getDecisions(scopeId, ver, after) {
  return answer_(function () {
    me_();
    var sc = scope_(scopeId), st = rows_(sc, Math.max(Number(after) || 0, Number(sc.store_cursor) || 1));
    return {ver: sc.ver, published: sc.published, records: st.recs, cursor: st.last};
  });
}
function decide(scopeId, ver, records, cursor) { return write_(scopeId, ver, records, cursor, false); }
function recordItems(scopeId, ver, records, cursor) { return write_(scopeId, ver, records, cursor, true); }

// ---- milestone 0 spike: <web app url>?spike=1 --------------------------------------------
// Shows what Session.getActiveUser() returns for whoever opens it, and times a 1 MB round trip.

function spike(kb) {
  var n = Math.max(0, Math.min(Number(kb) || 0, 4096)), chunk = new Array(1025).join('x');
  return {active: Session.getActiveUser().getEmail(), effective: Session.getEffectiveUser().getEmail(),
          now: now_(), payload: new Array(n + 1).join(chunk)};
}
function spikePage_() {
  var html = '<!doctype html><meta charset="utf-8"><title>review app spike</title>' +
    '<body style="font:14px system-ui;margin:2rem"><h3>review app: identity and payload check</h3><pre id="o">asking…</pre><script>' +
    'var o=document.getElementById("o"),t0=Date.now();' +
    'google.script.run.withFailureHandler(function(e){o.textContent="failed: "+e.message;}).withSuccessHandler(function(a){' +
    'var t1=Date.now();o.textContent="you are (active user): "+(a.active||"(EMPTY: the app cannot tell who you are)")+"\\nscript runs as:        "+a.effective+"\\nserver time:           "+a.now+"\\nempty round trip:      "+(t1-t0)+" ms\\n1 MB round trip:       timing…";' +
    'google.script.run.withSuccessHandler(function(b){o.textContent=o.textContent.replace("timing…",(Date.now()-t1)+" ms ("+b.payload.length+" bytes)");}).spike(1024);' +
    '}).spike(0);<\/script>';
  return HtmlService.createHtmlOutput(html).setTitle('review app spike');
}
